# Generated by Django 4.2 on 2023-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0004_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='nif',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userautonomo',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userautonomo',
            name='dni',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
