# Generated by Django 4.2 on 2023-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0005_alter_company_nif_alter_userautonomo_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('cost_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('stock_min', models.IntegerField()),
                ('iva', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
