# Generated by Django 4.2 on 2023-05-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0009_product_company_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_belongs_to', to='autonomo.company'),
        ),
    ]
