# Generated by Django 4.2 on 2023-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0014_invoice_iva_invoice_subtotal_invoice_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='iva',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
