# Generated by Django 4.2 on 2023-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0015_alter_invoice_iva_alter_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='iva',
            field=models.FloatField(null=True),
        ),
    ]
