# Generated by Django 4.2 on 2023-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0016_invoiceline_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='iva',
            field=models.FloatField(),
        ),
    ]
