# Generated by Django 4.2 on 2023-05-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autonomo', '0017_alter_invoiceline_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accounting_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_belong_to', to='autonomo.accountingyear'),
        ),
    ]
